scalar DateTime

type User {
    id: ID!
    name: String!
    email: String!
}

enum KnowledgeType {
    technology
    concept
    algorithm
    database
}

enum Relation {
    uses
    related_to
    part_of
    depends_on
    built_with
    extends
}

type Knowledge {
    id: ID!
    title: String!
    description: String!
    type: KnowledgeType!
    tags: [String!]!
    user: User!
    createdAt: DateTime!
    updatedAt: DateTime!
}

type Connection {
    id: ID!
    userId: ID!
    source: Knowledge!
    target: Knowledge!
    relation: Relation!
    createdAt: DateTime!
    updatedAt: DateTime!
}

type Query {
    knowledge: [Knowledge!]!
    knowledgeById(id: ID!): Knowledge
    connection: [Connection!]!
    connectionByKnowledge(id: ID!): [Connection!]!
}

input CreateKnowledgeInput {
    title: String!
    description: String!
    type: KnowledgeType!
    tags: [String!]!
    userId: ID!
}

input UpdateKnowledgeInput {
    title: String
    description: String
    type: KnowledgeType
    tags: [String!]
}

input CreateConnectionInput {
    userId: ID!
    sourceId: ID!
    targetId: ID!
    relation: Relation!
}

input UpdateConnectionInput {
    relation: Relation
}

type Mutation {
    createKnowledge(input: CreateKnowledgeInput!): Knowledge!

    updateKnowledge(id: ID!, input: UpdateKnowledgeInput!): Knowledge!

    deleteKnowledge(id: ID!): Boolean!

    createConnection(input: CreateConnectionInput!): Connection!

    updateConnection(id: ID!, input: UpdateConnectionInput): Connection!

    deleteConnection(id: ID!): Boolean!
}
